### ISSUE TITLE
More control over unused arguments

### ISSUE THREAD

**Issue by za-creature** [za-creature/coffeescope#11]
Implement something akin to the "after-used" value [in eslint](http://eslint.org/docs/rules/no-unused-vars.html#args)

Ref #7

**Comment by nmccready** [comment]
Is there any commenting system to tell it to ignore currently?

**Comment by za-creature** [comment]
`# noqa` drops all warnings on the current line (this applies to all coffeelint errors, not just coffeescope)

Note that 1.0 is around the block and will support this (don't want to give an ETA b/c I don't want to lie)

**Comment by nmccready** [comment]
> Is there any commenting system to tell it to ignore currently?

nvm this is good enough for me right now `# coffeelint: disable=check_scope` then `# coffeelint: enable=check_scope`

**Comment by za-creature** [comment]
You can also PR a `# noscope` shortcut for `# coffeelint: disable-line=check-scope` if you want to, though I'm not 100% that'll get approved:

https://github.com/clutchski/coffeelint/blob/a5babd23aa094132c0bdf97d47e639650aec72a5/src/line_linter.coffee#L75

**Comment by zacronos** [comment]
Ah cool, I came here to open an issue on exactly this.

Carry on.

**Comment by nmccready** [comment]
@za-creature if and when this feature gets added can you add explicit documentation on the coffeelint disables in the readme that are custom to this repo.

**Comment by za-creature** [comment]
wdym? `# noqa` is a part of coffeelint https://github.com/clutchski/coffeelint/pull/552/commits/0e68c705de252c52002f345321c929455dbade47

**Comment by nmccready** [comment]
No I am referring to unused args.

**Comment by za-creature** [comment]
Like this: https://github.com/za-creature/coffeescope/blob/1.0/README.md#unused-arguments ?

**Comment by nmccready** [comment]
Also what do you think of the following API for having opt outs?

coffeelint.json
```
    "check_scope" : {
        "module":"coffeescope2",
        "level": "warn",
        "environments": ["builtin","es5","browser","es6","node","mocha","shelljs","jquery"],
        "globals": {},
        "overwrite": false,
        "shadow": true,
        "shadow_builtins": false,
        "shadow_exceptions": ["err", "next"],
        "undefined": true,
        "hoist_local": false,
        "hoist_parent": true,
        "unused_variables": [/.*\/config/logger.*/], #true but opt out regexes?
        "unused_arguments": false
    }
```

**Comment by nmccready** [comment]
> Like this: https://github.com/za-creature/coffeescope/blob/1.0/README.md#unused-arguments ?

Yes exactly; I didn't see the 1.X branch thank you.

**Comment by za-creature** [comment]
> Also what do you think of the following API for having opt outs?

If you're suggesting the exception be path-based, then I don't think that's possible: this plugin operates on the AST and I'm not even sure coffeelint passes the filename to plugins,

To solve your problem (if I understood it correctly), I'd just add `# coffeelint: disable=check_scope` for each file you want to skip. Having to go through all the files is a hassle, but it gives you a chance to evaluate on a per-file basis if it's worth fixing the scope errors or just tell the linter to fuck off.

If what you're suggesting instead is that the exception be name-based, that's actually already implemented in `shadow_exceptions`: `err` and `next` are actually regexps; you could write `err.*` and it'll ignore all shadow errors for vars starting with `err`. However, this behavior isn't yet consolidated and is only available for shadow messages. 1.0 will have this option for unused and overwrite as well (though not undefined, as those should be fixed with `globals` and `environments` instead)

**Comment by nmccready** [comment]
Actually It is not a path based check. Just a text based check.

Example: 

Let's say we have an unused logger in our code bade many times.

Where we want:

- to be bad / flag error:

`logger = require('some_where/logger')`

- to pass

`logger = require('some_where/logger').spawn("domain")`

So basically an opt out of:

`/logger = require\(.*logger).spawn\(.*\)/`

**Comment by za-creature** [comment]
If you're not going to use `logger` anywhere in your code, why bind it to a var?

`require("somewhere/logger").spawn("domain")` is perfectly valid, and fairly common: `require('coffee-script').register()`

**Comment by nmccready** [comment]
I understand your point; but we turn loggers on an off at will and it is better to just leave it defined and not used. But defined correctly via spawn.

**Comment by nmccready** [comment]
Most of the time I agree where I want them (unused_vars) to be errors/warnings. However, this is an exception to the rule. Anyway, I was just looking for a clean way to not have to put 
`# coffeelint: disable=check_scope` around my loggers everywhere.

**Comment by za-creature** [comment]
Sorry dude, I think your request falls outside of this project's scope:

> leave it defined and not used

While not supported right now, you will be able to skip this warning by adding `"logger"` to `unused_except` in 1.0

> defined correctly via spawn

coffeescope can't tell what's correct and what's not beyond basic scoping rules; my guess is that you're looking for a plugin that generates an error for lines that match a certain regexp, e.g. `/require\(".*/logger"\)$/` which is an interesting idea. Unfortunately not one I am able to pursue at the moment as I'm already stretched thin (it used to be that issues would get closed and the fix released in <24h; that has stopped being the case since quite some time ago)

**Comment by nmccready** [comment]
@za-creature right I am basically just wondering if it is feasible incase I might try adding this feature to the repo. I don't want to work on it, if it has no chance of being merged.

**Comment by za-creature** [comment]
No, I don't think I'd accept such a PR as to me it seems to do something completely unrelated to variables. Besides, being an AST linter, you'd have to go out of your way to just obtain individual lines that you can match your regexps against.

If you decide to implement this yourself, I'd suggest you implement it as a line linter plugin ([example](https://github.com/clutchski/coffeelint/blob/master/src/rules/eol_last.coffee)) which should make your life much easier

**Comment by nmccready** [comment]
Cool thanks for the fast replies.

**Comment by zmillman** [comment]
@za-creature I'm really excited for that `unused_except` - any estimates on when the 1.0 branch will be merged to master?

**Comment by za-creature** [comment]
@zmillman hey, sorry for the late reply, there's a lot of unrest in my country right now, and that's consuming most of my free time; 1.0 is far away from a public release (I'd say I'm at about 25% there right now), but luckily, this project is small enough that it doesn't necessarily mean it'll take months to complete (first usable version was written in a couple of days, so even a complete rewrite might only take a few weeks or so)

Assuming I can allocate this project the time it deserves (which right now I can't promise), you're looking at maybe 1 month until a release candidate.

**Comment by zmillman** [comment]
@za-creature take all the time you need!

We've already gotten a ton of use out of the current version (it's stopped several dumb bugs going to production) and I really appreciate the work you've put into it. Being politically involved is way more important though 😄
