### ISSUE TITLE
One-line require/export oddity

### ISSUE THREAD

**Issue by bazineta** [za-creature/coffeescope#14]
We have a trampoline module that does nothing but make a native module a bit easier for callers, debugging, etc.

```
module.exports = require './build/Release/authentication'
```

There is seemingly no way to convince coffeescope that 'module' and 'require' aren't undefined identifiers.  This is in a large codebase of about 900 other files, all of which it seems quite content with given our 'environments' property.  Not sure why it's got its grump on about just this one.

**Comment by za-creature** [comment]
Could it be folder-structure related? Maybe coffeelint isn't picking up your package.json / coffeelint.json file relevant to that particular file?

Can you reproduce this in a controlled environment? I'd love to help out, but I'm going to need a bit more than that to work with.

**Comment by bazineta** [comment]
Aha, yes, your suggestion was spot on. There's a package.json in that particular directory relevant to building the native module, and it lacked coffeelint configuration directives, which we put in our main package.json.  Adding the relevant ones to the directory-specific package.json resolved the issue.  Thanks!
