### ISSUE TITLE
Errors when variable name is in Object.getOwnPropertyNames(Object.prototype)

### ISSUE THREAD

**Issue by saifelse** [za-creature/coffeescope#15]
The following list of variable names:
[ 'constructor', 'toString', 'toLocaleString', 'valueOf', 'hasOwnProperty', 'isPrototypeOf', 'propertyIsEnumerable', '**defineGetter**', '**lookupGetter**', '**defineSetter**', '**lookupSetter**', '**proto**' ]

(e.g. `constructor = 123`)

will cause coffeescope to error because `if not @symbols[name]` will never evaluate to true, since the above listed properties are always on `@symbols`, an instance of Object. One workaround would be to prefix all the keys, e.g. `if not @symbols['somePrefix_' + name]` which seems pretty hacky. Cleaner solution seem to be using a Map polyfill (e.g. `require('core-js/es6/map')` from https://github.com/zloirock/core-js )

**Comment by za-creature** [comment]
Good catch. Fixed in 0.3.1
