### ISSUE TITLE
more control over unused variables from destructured assignment

### ISSUE THREAD

**Issue by zacronos** [za-creature/coffeescope#35]
Similar to #11 and #7, it would be nice to be able make something like this:
```coffeescript
str = 'ABCD_1234_abcd'
[caps, digits, lower] = str.split('_')
console.log("Found #{digits} and #{lower}!")
```

Without triggering the unused variable rule on `caps`.

**Comment by dbushong** [comment]
Same rules as for unused function args, IMO.  OK to have non-terminal extras, since they're probably just there for positional spacing.

**Comment by zmillman** [comment]
This might have been resolved by https://github.com/za-creature/coffeescope/pull/39
