### ISSUE TITLE
inline disable syntax

### ISSUE THREAD

**Issue by wesvetter** [za-creature/coffeescope#36]
Is there any syntax for disabling directives besides `# noqa`?

For example, say I want to ignore the overwrite warning in `set_user`: 

```coffeescript
_user = null
get_user = -> _user
set_user = (u) -> _user = u
module.exports =
  get_user: get_user
  set_user: set_user
```

This will work:

```coffeescript
_user = null
get_user = -> _user
set_user = (u) -> _user = u # noqa
module.exports =
  get_user: get_user
  set_user: set_user
```

But this does not:
```coffeescript
_user = null
get_user = -> _user
# coffeelint: disable=overwrite
set_user = (u) -> _user = u
# coffeelint: enable=overwrite
module.exports =
  get_user: get_user
  set_user: set_user
```

**Comment by za-creature** [comment]
Coffeescope does not currently export multiple rules; you'll have to use `# coffeelint: disable=coffeescope2`

Leaving this open because I may investigate splitting into multiple rules at a logical level. See also #3

**Comment by wesvetter** [comment]
`# coffeelint: disable=coffeescope2` didn't work, but `disable=check_scope` does (at least on the trivial example below).

```coffeescript
_user = null
get_user = -> _user
# coffeelint: disable=check_scope
set_user = (u) -> _user = u
module.exports =
  get_user: get_user
  set_user: set_user
```

`check_scope` is the parent attribute in `coffeelint.json`, is that what I should be disabling? Or am I inadvertently disabling something else in regular Coffeelint?

**Comment by za-creature** [comment]
Sorry, my bad. You are doing it right, you have to disable the rule by name, not by module.

**Comment by wesvetter** [comment]
Awesome. Would you like me to make a PR adding a bit to the README about `noqa`/disabling lines? It took me a bit of digging just to find the `# noqa` option (and figuring out that it only works on the same line).

**Comment by za-creature** [comment]
`# noqa` is actually a [coffeelint feature](https://github.com/clutchski/coffeelint/blob/master/src/line_linter.coffee#L75) so please PR it there

**Comment by wesvetter** [comment]
👍 done. https://github.com/clutchski/coffeelint/pull/598
