### ISSUE TITLE
CS 2.3.0 - For loop AST change

### ISSUE THREAD

**Issue by bazineta** [za-creature/coffeescope#42]
There's a change to for loop AST generation in CS 2.3.0:

https://github.com/jashkenas/coffeescript/pull/4893

This breaks the ScopeLinter, as `node.body` will now not necessarily contain `locationData`.

I suspect but am not certain as of yet that just adding a conditional prior the property analysis for loop in the visitFor() method will resolve the breakage. The tests pass and it would be backward compatible, but I need to do more comprehensive testing.

Just bringing this up in case others have the problem and to get the opinions of others at this point.

```coffeescript
    visitFor: (node) =>
        # because comprehensions compile to the same AST as regular for blocks
        # we distinguish between the two by checking bounds: a comprehension's
        # body has the same location as the node itself, whereas for a regular
        # for, the body is contained within the for block
        comprehension = true
        if node.body.locationData?
            for prop in ["first_line", "first_column", "last_line", "last_column"]
                if node.locationData[prop] isnt node.body.locationData[prop]
                    comprehension = false
                    break

        if node.name?
            @visitAssignment(node.name, {comprehension})
        if node.index?
            @visitAssignment(node.index, {comprehension})
        node.eachChild(@visit)
        undefined
```

**Comment by za-creature** [comment]
Thanks!
