### ISSUE TITLE
Some issues to discuss

### ISSUE THREAD

**Issue by mwager** [za-creature/coffeescope#6]
Hey, I really like your project and it looks good to our team. There are some issues though I want to discuss here:
### 1) Loop variables are never read

```
for key, val of someObject
  doSomethingWith(val)
```

gives me:

```
✗ #1: Variable "key" is never read ( first defined on line 1).
```

Is there an option to ignore this? I know I could write this in another way but it's nice to use the `for ... of` syntax here.
### 2) Undefined identifier if used before defined

```
foo()

foo = ->
  return 1
```

gives:

```
✗ #1: Undefined identifier "foo".
✗ #3: Variable "foo" is never read ( first defined on line 3).
```

This cannot be correct because `foo` is defined within the scope.
### 3) Variable never read

```
describe 'some spec', ->

  foo = null

  beforeEach ->
    foo = 1
```

gives:

```
✗ #3: Variable "foo" is never read ( first defined on line 3).
✗ #6: Variable "foo" is never read ( first defined on line 3).
```

Same:

```
intervalId = setInterval ->
  clearInterval intervalId
, 50
```

-> Variable "intervalId" is never read

**Comment by za-creature** [comment]
Thanks for the reports!

To ease communication and tracking, I'm going to split all mentioned issues in separate requests!
