### ISSUE TITLE
Allow unused loop variables

### ISSUE THREAD

**Issue by za-creature** [za-creature/coffeescope#7]
Split from #6 

``` coffeescript
for key, val of someObject
  doSomethingWith(val)
```

gives me:

```
✗ #1: Variable "key" is never read ( first defined on line 1).
```

Is there an option to ignore this? I know I could write this in another way but it's nice to use the for ... of syntax here.

**Comment by zmillman** [comment]
I think this was also resolved by https://github.com/za-creature/coffeescope/pull/39 (use `_key` as your variable name to match the ignore pattern)
