### ISSUE TITLE
Support hoisting

### ISSUE THREAD

**Issue by za-creature** [za-creature/coffeescope#8]
Split from #6 

``` coffeescript
foo()

foo = ->
  return 1
```

gives:

```
✗ #1: Undefined identifier "foo".
✗ #3: Variable "foo" is never read ( first defined on line 3).
```

This cannot be correct because foo is defined within the scope.

**Comment by za-creature** [comment]
Currently, the `undefined` rule is implemented with [no-use-before-define](http://eslint.org/docs/rules/no-use-before-define) semantics. I agree that this is not what most coffeescript developers expect and while I definitely want to keep the current behavior in as an option, the default should be to allow hoisting

**Comment by mwager** [comment]
Why did you close this issue?

**Comment by za-creature** [comment]
Because it landed in 0.2: https://github.com/za-creature/coffeescope/blob/master/test/ScopeLinter/hoist.coffee#L12

**Comment by za-creature** [comment]
I may have forgotten to update the default behavior; sorry :(

**Comment by mwager** [comment]
nice thx!
